[versions]
agp = "8.5.0"
androidGifDrawable = "1.2.10"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
languageId = "17.0.5"
material = "1.10.0"
roomRuntime = "2.3.0"
roomRuntimeVersion = "2.6.1"
translate = "17.0.2"
uiAndroid = "1.6.8"
preference = "1.2.0"
workRuntime = "2.9.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

[libraries]
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
language-id = { module = "com.google.mlkit:language-id", version.ref = "languageId" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-runtime-v261 = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
translate = { module = "com.google.mlkit:translate", version.ref = "translate" }
ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

